app = "roblox-ban-system"

[build]
  builder = "heroku/buildpacks:20"

[env]
  ADMIN_PASSWORD = "Tutuu666kMM32910"
  
[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    restart_limit = 0
